### ISSUE TITLE
NOne when?

### ISSUE THREAD

**Issue by Derpthemeus** [pseudonym117/YasuNO#1]
Alternatively YoNAY

**Comment by Derpthemeus** [comment]
I've done some market research, and I think we should callnit YoNAY 
![Screenshot_20200818-115710_Twitter](https://user-images.githubusercontent.com/16827162/90536600-4504e680-e14a-11ea-93ac-d6092252f7b5.jpg)

**Comment by Derpthemeus** [comment]
So I guess we actually ended up resolving this issue. I'm just as surprised as y'all. https://github.com/YasuNO-LLC/YoNAY

**Comment by pseudonym117** [comment]
honestly its amazing. well done.
