### ISSUE TITLE
Feature Request: Adding Support for Yone

### ISSUE THREAD

**Issue by DomiiBunn** [pseudonym117/YasuNO#10]
**Description:**
As an enthusiastic user of YasuNO, I have experienced firsthand the transformative effects of your tool in improving the League of Legends experience by curbing the rampant feeding and frustration associated with Yasuo mains. However, as the meta evolves and new champions emerge, it has become increasingly evident that the influence of certain champions extends beyond Yasuo alone.

I hereby request the addition of support for Yone, the brother-turned-enemy of Yasuo, to the YasuNO tool. Similar to Yasuo, Yone's presence in champion select often elicits groans of dismay and apprehension from teammates and opponents alike. With his high skill ceiling and potential for catastrophic misplays, Yone shares many of the characteristics that make Yasuo mains a source of contention within the League of Legends community.

**Benefits:**
- **Comprehensive Coverage:** By extending support to include Yone, YasuNO will ensure a more thorough approach to promoting balanced gameplay and positive player experiences. Users will no longer have to contend with the unpredictability and frustration associated with Yone mains, further enhancing the integrity of matches and fostering a more enjoyable environment for all.

**Implementation Details:**
Integrating support for Yone into YasuNO would involve modifying the tool's detection algorithms to recognize attempts to select Yone in champion select. Upon detection, YasuNO would automatically intervene, redirecting users to choose a different champion in order to prevent the disruptive influence of Yone mains on gameplay outcomes.

**Conclusion:**
By heeding this request and adding support for Yone to the YasuNO tool, your team would demonstrate a proactive commitment to addressing emerging challenges within the League of Legends community. Together, we can work towards creating a more balanced and harmonious gaming environment, free from the detrimental effects of champions like Yasuo and Yone.

Thank you for considering my request. I eagerly anticipate the possibility of experiencing the benefits of an expanded YasuNO toolset and remain committed to supporting your efforts to enhance the League of Legends experience for players worldwide.

Sincerely,

**Comment by Derpthemeus** [comment]
Please see https://github.com/YasuNO-LLC/YoNAY

Brilliant idea If I do say so myself
